export const SITE_SETTINGS_VERSION = 5;

export const SITE_ICON_OPTIONS = [
  "monitor",
  "wallet",
  "badge-percent",
  "hammer",
  "rocket",
  "package",
  "refresh-euro",
  "shield",
  "headset",
];

export const DEFAULT_SITE_SETTINGS = {
  version: SITE_SETTINGS_VERSION,
  site: {
    navigation: {
      brandName: "DatorHuset",
      logoUrl: "/Datorhuset.png",
      menuLabel: "Meny",
      searchPlaceholder: "Sök bland produkter, komponenter och kategorier",
      adminPortalHref: "https://admin.datorhuset.site",
      menuItems: [
        { label: "Alla produkter", href: "/products" },
        { label: "Custom Bygg", href: "/custom-bygg" },
        { label: "Service & Reparation", href: "/service-reparation" },
        { label: "Kundservice & Kontakta oss", href: "/kundservice" },
      ],
    },
    footer: {
      supportTitle: "Kundservice",
      supportEmail: "support@datorhuset.site",
      supportHours: "Svarstider 11:00-15:00",
      logoUrl: "/Datorhuset.png",
      columns: [
        {
          title: "Kontakta oss",
          links: [
            { label: "FAQ", href: "/faq" },
            { label: "Kundservice / Kontaktuppgifter", href: "/kundservice" },
            { label: "Om oss", href: "/about" },
            { label: "Integritetspolicy", href: "/privacy-policy" },
            { label: "Allmänna villkor", href: "/terms-of-service" },
          ],
        },
        {
          title: "Våra tjänster",
          links: [
            { label: "Våra datorer", href: "/products" },
            { label: "Custom bygg", href: "/custom-bygg" },
            { label: "Service / reparation", href: "/service-reparation" },
          ],
        },
      ],
      socialLinks: [
        { platform: "instagram", label: "Instagram", href: "https://www.instagram.com/datorhuset_uf/" },
        { platform: "x", label: "X", href: "https://x.com/DatorHuset_UF" },
        { platform: "tiktok", label: "TikTok", href: "https://www.tiktok.com/@datorhuset_uf?lang=en-GB" },
        { platform: "youtube", label: "YouTube", href: "https://www.youtube.com/@DatorHuset" },
      ],
      copyright: "©2026 DatorHuset UF. Alla rättigheter förbehållna.",
    },
    motion: {
      heroRevealDurationMs: 720,
      heroRevealStaggerMs: 120,
      bannerRevealDurationMs: 680,
      bannerRevealDistancePx: 18,
      cardHoverScale: 1.03,
    },
  },
  homepage: {
    hero: {
      title: "Veckans bygg!",
      subtitle: "Elektronik för företag",
      featureEyebrow: "Nyhet!",
      featureTitle: "Platina Curver är nu i lager!",
      featureImage: "/images/foretagsdeal.webp",
      featureImageAlt: "Gamingdator för företagserbjudande",
      secondaryTitle: "Veckans deal - få en gåva vid köpet!",
      secondaryDescription: "Få en exklusiv gåva när du handlar hos oss.",
      secondaryBadge: "Gåva vid köp",
      secondaryNote: "Musmatta, tangentbord, mus eller uppgraderade komponenter!",
      categoriesTitle: "Populära kategorier",
      categories: [
        { name: "Alla produkter", icon: "monitor", href: "/products?clear_filters=1" },
        { name: "Budgetvänliga", icon: "wallet", href: "/products?category=budget&clear_filters=1" },
        { name: "Pris/prestanda", icon: "badge-percent", href: "/products?category=price-performance&clear_filters=1" },
        { name: "Custom Bygg", icon: "hammer", href: "/custom-bygg" },
        { name: "Bästa prestanda", icon: "rocket", href: "/products?category=toptier&clear_filters=1" },
      ],
      featuredTitle: "Senast visade produkter",
      featuredCount: 6,
      featuredInventoryLabel: "I lager",
    },
    steps: {
      title: "Att köpa en riktigt bra dator har aldrig varit så lätt",
      description: "Så här köper du din dator via vår tjänst",
      primaryLabel: "Köp din dator",
      primaryHref: "/products",
      secondaryLabel: "Gör en custom bygg",
      secondaryHref: "/custom-bygg",
      items: [
        {
          title: "1. Gör en preorder",
          description: "Hitta ett brett utbud av datorer eller skicka in ett custom-bygge du vill ha.",
          icon: "monitor",
        },
        {
          title: "2. Vi bygger och packar din dator",
          description:
            "Vi köper komponenterna och bygger datorn. Byggtiden varierar från 3 dagar till några veckor beroende på om du beställer en helt ny dator, en dator med begagnade komponenter eller en custom-bygg. Se FAQ för mer information.",
          icon: "package",
        },
        {
          title: "3. Leverans/hämta upp",
          description: "Datorn är byggd och klar. Hämta upp den eller välj fraktalternativ.",
          icon: "refresh-euro",
        },
      ],
    },
    promo: {
      eyebrow: "Mer från DatorHuset",
      title: "Vi bygger, fixar och optimerar för dig",
      description:
        "Välj service om du vill få din dator tillbaka i toppform eller bygg ett helt nytt system från grunden.",
      cards: [
        {
          eyebrow: "Service & reparation",
          title: "Vi får din dator tillbaka i toppform",
          description:
            "Snabb felsökning, tydlig offert och proffsig optimering. Vi tar hand om allt från prestandaproblem till uppgraderingar.",
          image: "/products/newpc/cg530_new.png",
          imageAlt: "Service och reparation av datorer",
          bullets: [
            "Felsökning inom 24 timmar på vanliga fel",
            "Rengöring, kylning och stabilitetstester",
            "Garanti på utfört arbete och uppgraderingar",
          ],
          primaryLabel: "Service & reparation",
          primaryHref: "/service-reparation",
          secondaryLabel: "Fråga en tekniker",
          secondaryHref: "/kundservice",
        },
        {
          eyebrow: "Custom bygg",
          title: "Byggd för din vardag och din gaming",
          description:
            "Välj komponenter, stil och budget. Vi bygger, testar och levererar en dator som är helt anpassad efter dig.",
          image: "/products/newpc/allwhite-1.jpg",
          imageAlt: "Custom byggda datorer",
          bullets: [
            "Välj prestandanivå, formfaktor och RGB",
            "Optimerade för gaming, kreativt arbete eller AI",
            "Trygg leverans med test och verifiering",
          ],
          primaryLabel: "Gå till custom bygg",
          primaryHref: "/custom-bygg",
          secondaryLabel: "Se färdiga datorer",
          secondaryHref: "/products",
        },
      ],
    },
  },
  pages: {
    products: {
      banners: {
        default: {
          eyebrow: "Topplistan",
          title: "Bästa säljare inom stationära datorer i hela Norden!",
          description: "Utvalda byggen som levererar prestanda, design och trygg service.",
          images: [],
          stickers: [],
          primaryLabel: "Se alla datorer",
          primaryHref: "/products",
          secondaryLabel: "Custom bygg",
          secondaryHref: "/custom-bygg",
        },
        budget: {
          eyebrow: "Budgetvänliga",
          title: "Budget betyder inte dåligt",
          description: "Smarta val som håller priset nere utan att tumma på känslan.",
          images: [],
          stickers: ["Bäst i budgetklass"],
          primaryLabel: "Se budgetdatorer",
          primaryHref: "/products?category=budget&clear_filters=1",
          secondaryLabel: "Fråga oss",
          secondaryHref: "/kundservice",
        },
        "best-selling": {
          eyebrow: "Mest för pengarna",
          title: "Mest för pengarna",
          description: "Våra mest prisvärda byggen - noggrant utvalda för maximal valuta.",
          images: [],
          stickers: ["DatorHusets val", "Mest valuta", "Otrolig prestanda"],
          primaryLabel: "Se favoriterna",
          primaryHref: "/products?category=best-selling&clear_filters=1",
          secondaryLabel: "Custom bygg",
          secondaryHref: "/custom-bygg",
        },
        "price-performance": {
          eyebrow: "Pris/prestanda",
          title: "Pris/prestanda",
          description: "Byggen med starkast balans mellan pris och prestanda.",
          images: [],
          stickers: ["Mest för pengarna"],
          primaryLabel: "Se pris/prestanda",
          primaryHref: "/products?category=price-performance&clear_filters=1",
          secondaryLabel: "Jämför alternativ",
          secondaryHref: "/kundservice",
        },
        toptier: {
          eyebrow: "Bästa prestanda",
          title: "När bara det snabbaste duger",
          description: "Toppbyggen för dig som vill ha maximal kraft och kompromisslös kvalitet.",
          images: [],
          stickers: ["Topline"],
          primaryLabel: "Se toppmodeller",
          primaryHref: "/products?category=toptier&clear_filters=1",
          secondaryLabel: "Bygg din egen",
          secondaryHref: "/custom-bygg",
        },
      },
    },
    serviceRepair: {
      heroEyebrow: "Service & reparation",
      heroTitle: "Vi reparerar, uppgraderar och optimerar din dator",
      heroDescription:
        "DatorHuset hjälper dig med allt från felsökning till komplett uppgradering. Snabb respons, tydlig offert och service som sätter prestanda i fokus.",
      primaryLabel: "Kontakta service",
      primaryHref: "/kundservice",
      secondaryLabel: "Se våra datorer",
      secondaryHref: "/products",
      flowTitle: "Lämna in på reparation? Börja här.",
      flowDescription: "Vårt flöde är byggt för tydlighet och snabbhet. Du vet vad som sker och när.",
      steps: [
        {
          value: "step-1",
          title: "1. Felsök din enhet",
          body: "Beskriv felet så noggrant du kan. Våra tekniker analyserar och återkommer snabbt.",
        },
        {
          value: "step-2",
          title: "2. Godkänn offert",
          body: "Vi svarar med rekommendation, prisbild och tidsplan. Du får en tydlig offert innan vi startar. Inga dolda kostnader.",
        },
        {
          value: "step-3",
          title: "3. Service och test",
          body: "Vi reparerar, uppgraderar och stresstestar för att säkerställa stabilitet.",
        },
        {
          value: "step-4",
          title: "4. Hämta upp eller få leverans",
          body: "Vi meddelar när din dator är klar. Välj hämtning eller leverans. Se instruktioner i Mina beställningar.",
        },
        {
          value: "step-5",
          title: "5. Efterservice",
          body: "Behov av finjustering? Vi finns kvar för support och tips.",
        },
      ],
      formTitle: "Beskriv ditt problem",
      formDescription: "Fyll i formuläret så kan vi snabbare hjälpa dig rätt. Ju mer detaljer, desto bättre offert.",
    },
    customerService: {
      heroEyebrow: "Kundservice",
      heroTitle: "Kontakta oss",
      heroDescription: "Behöver du hjälp med en beställning, service eller garanti? Vi svarar snabbt med tydliga besked.",
      heroImage: "/Datorhuset.png",
      heroImageAlt: "DatorHuset logo",
      heroCtaLabel: "Se FAQ",
      heroCtaHref: "/faq",
      contactTitle: "Kontaktuppgifter",
      contactEmail: "support@datorhuset.site",
      hoursTitle: "Öppettider",
      hoursLines: ["Svarstider på mejl: 11:00 - 03:00", "Vi svarar på mejl både under vardagar och helger."],
      supportTitle: "Supportärenden",
      supportLines: [
        "För frågor om beställningar, returer eller fakturor: ange ordernummer och beskriv ärendet kort.",
        "Teknisk support: beskriv problemet, vilka komponenter som används och bifoga bilder om möjligt.",
      ],
      commonIssuesTitle: "Vanliga ärenden",
      commonIssues: [
        "Orderstatus, leveranstider och spårning",
        "Ändringar i beställning eller uppgraderingar",
        "Garantifrågor och reklamation",
        "Felsökning, service och reparation",
        "Företagslösningar och faktura",
      ],
      commonIssuesNote: "Vi återkommer normalt inom 24 timmar på vardagar.",
      workflowTitle: "Så arbetar vi",
      workflowSteps: [
        "Du beskriver ditt ärende via mejl eller formulär.",
        "Vi återkommer med frågor eller förslag.",
        "Du får en tydlig offert och tidsplan.",
        "Vi uppdaterar dig när arbetet är klart.",
      ],
      workflowCtaLabel: "Starta serviceärende",
      workflowCtaHref: "/service-reparation",
    },
  },
};
